// Shared content data — pins visible on the map

export const CONTENT_ITEMS = [
  // ── HARVARD CAMPUS ──────────────────────────────────────────
  {
    id: 1, type: 'resource',
    title: 'Harvard International Office (HIO)',
    body: 'Your first stop for all visa, immigration, and OPT/CPT questions. Walk-in hours Mon–Fri 9am–5pm.',
    location: { lat: 42.3784, lng: -71.1173, label: 'Smith Campus Center' },
    username: 'SHINE Official', initials: 'SO',
    avatarBg: 'linear-gradient(135deg, #3CB87A, #1A9A5A)',
    likes: 142, comments: 12, time: 'Pinned',
  },
  {
    id: 2, type: 'question',
    title: 'How do I open a US bank account as an international student?',
    body: 'I just arrived and need to set up banking. Do I need an SSN? Any banks that are student-friendly?',
    location: { lat: 42.3762, lng: -71.1155, label: 'Harvard Square' },
    username: 'Mei Lin', initials: 'ML',
    avatarBg: 'linear-gradient(135deg, #FFD6B0, #FF9A3C)',
    likes: 24, comments: 8, time: '2h ago',
  },
  {
    id: 3, type: 'tip',
    title: 'Best quiet study spot: Lamont Library 3rd floor stacks',
    body: 'Almost nobody goes there. Bring headphones, natural light is great in the morning. Open until midnight on weekdays.',
    location: { lat: 42.3741, lng: -71.1161, label: 'Lamont Library' },
    username: 'Lucas M.', initials: 'LM',
    avatarBg: 'linear-gradient(135deg, #B8FFD0, #3CB87A)',
    likes: 87, comments: 15, time: '5h ago',
  },
  {
    id: 4, type: 'story',
    title: 'My first morning walk through Johnston Gate',
    body: 'I arrived jet-lagged at 6am and walked through Johnston Gate in the fog. Nobody else was around. One of those moments I\'ll never forget.',
    location: { lat: 42.3770, lng: -71.1167, label: 'Johnston Gate' },
    username: 'Ji-ho P.', initials: 'JP',
    avatarBg: 'linear-gradient(135deg, #F0C8FF, #CC66FF)',
    likes: 201, comments: 34, time: '1d ago',
  },
  {
    id: 5, type: 'tip',
    title: 'Get to Annenberg 5 min before opening — no queue',
    body: 'Shows up at exactly 7:25am and walk straight in. Wait even 10 minutes and the line wraps around the building.',
    location: { lat: 42.3730, lng: -71.1182, label: 'Annenberg Hall' },
    username: 'Priya S.', initials: 'PS',
    avatarBg: 'linear-gradient(135deg, #B8D8FF, #5599EE)',
    likes: 134, comments: 27, time: '2d ago',
  },
  {
    id: 6, type: 'activity',
    title: 'Harvard Coffee Shop Crawl ☕',
    body: 'Visit 5 local coffee spots around campus and share your review! Science Center, Crema, Darwin\'s, Peet\'s, and one hidden gem of your choice.',
    location: { lat: 42.3762, lng: -71.1148, label: 'Science Center' },
    username: 'Omar K.', initials: 'OK',
    avatarBg: 'linear-gradient(135deg, #FFE0B0, #FF8C00)',
    likes: 56, comments: 19, time: '3d ago',
    participants: 12, goal: 5,
  },
  {
    id: 7, type: 'question',
    title: 'Best way to get a CharlieCard for the T?',
    body: 'I keep paying cash on the subway. Is the CharlieCard worth getting? Where do I load it?',
    location: { lat: 42.3732, lng: -71.1190, label: 'Harvard T Station' },
    username: 'Sofia R.', initials: 'SR',
    avatarBg: 'linear-gradient(135deg, #FFB8C8, #EE4466)',
    likes: 45, comments: 11, time: '4h ago',
  },
  {
    id: 8, type: 'story',
    title: 'Morning runs along the Charles River',
    body: 'Wake up at 6:30, run down to the river. The sunrise over the water with the crew teams rowing — nothing like it. Highly recommend.',
    location: { lat: 42.3695, lng: -71.1070, label: 'Charles River Esplanade' },
    username: 'Kenji T.', initials: 'KT',
    avatarBg: 'linear-gradient(135deg, #B8D8FF, #5599EE)',
    likes: 178, comments: 22, time: '2d ago',
  },
  {
    id: 9, type: 'resource',
    title: 'Harvard HUHS — Free counseling for int\'l students',
    body: 'Harvard University Health Services offers free short-term counseling. No referral needed, just call to schedule. Really helped me with adjustment.',
    location: { lat: 42.3748, lng: -71.1188, label: 'Harvard University Health Services' },
    username: 'SHINE Official', initials: 'SO',
    avatarBg: 'linear-gradient(135deg, #3CB87A, #1A9A5A)',
    likes: 93, comments: 8, time: 'Pinned',
  },
  {
    id: 10, type: 'activity',
    title: 'Harvard Yard Sunrise Photo Challenge',
    body: 'Take a photo of Harvard Yard at sunrise (before 7am), post it here with the tag #SHINEsunrise. Best shot wins bragging rights.',
    location: { lat: 42.3755, lng: -71.1130, label: 'Harvard Yard' },
    username: 'Mei Lin', initials: 'ML',
    avatarBg: 'linear-gradient(135deg, #FFD6B0, #FF9A3C)',
    likes: 67, comments: 31, time: '5d ago',
    participants: 28, goal: 1,
  },
  {
    id: 11, type: 'tip',
    title: 'Harvard ID doubles as your library card, gym pass, AND T discount',
    body: 'Show your Harvard ID at the Harvard Square T station for a discounted semester pass. Also works at several local restaurants for student discounts.',
    location: { lat: 42.3770, lng: -71.1195, label: 'Harvard ID Office' },
    username: 'Lucas M.', initials: 'LM',
    avatarBg: 'linear-gradient(135deg, #B8FFD0, #3CB87A)',
    likes: 312, comments: 44, time: '1w ago',
  },

  // ── GLOBAL PINS (visible when zoomed out) ──────────────────
  {
    id: 12, type: 'story',
    title: 'The moment I got my Harvard acceptance email',
    body: 'I was in a café in Mumbai when the email arrived. I read it three times. Then I just sat there quietly for an hour. That\'s a moment I\'ll carry forever.',
    location: { lat: 19.0760, lng: 72.8777, label: 'Mumbai, India' },
    username: 'Priya S.', initials: 'PS',
    avatarBg: 'linear-gradient(135deg, #B8D8FF, #5599EE)',
    likes: 445, comments: 67, time: '6mo ago',
  },
  {
    id: 13, type: 'tip',
    title: 'Pack smart from Shanghai — don\'t overpack',
    body: 'I shipped 3 boxes and used maybe 10% of it. Amazon Prime delivers everything within 2 days. Just bring sentimental stuff and good shoes.',
    location: { lat: 31.2304, lng: 121.4737, label: 'Shanghai, China' },
    username: 'Mei Lin', initials: 'ML',
    avatarBg: 'linear-gradient(135deg, #FFD6B0, #FF9A3C)',
    likes: 289, comments: 52, time: '3mo ago',
  },
  {
    id: 14, type: 'question',
    title: 'Any other students from Seoul in Class of 2028?',
    body: 'Would love to connect before orientation. Share your Instagram or KakaoTalk below!',
    location: { lat: 37.5665, lng: 126.9780, label: 'Seoul, South Korea' },
    username: 'Ji-ho P.', initials: 'JP',
    avatarBg: 'linear-gradient(135deg, #F0C8FF, #CC66FF)',
    likes: 34, comments: 28, time: '2mo ago',
  },
  {
    id: 15, type: 'story',
    title: 'Saying goodbye to Berlin',
    body: 'Left Tegel airport at 5am. My whole family came. My dad held it together until security. I didn\'t. Arrived at Harvard 11 hours later — a completely different world.',
    location: { lat: 52.5200, lng: 13.4050, label: 'Berlin, Germany' },
    username: 'Sofia R.', initials: 'SR',
    avatarBg: 'linear-gradient(135deg, #FFB8C8, #EE4466)',
    likes: 512, comments: 89, time: '4mo ago',
  },
]

export const TYPE_CONFIG = {
  question: { color: '#5599EE', light: '#EEF4FF', label: 'Question' },
  tip:      { color: '#FF9A3C', light: '#FFF5EE', label: 'Tip' },
  story:    { color: '#CC66FF', light: '#F8EEFF', label: 'Story' },
  resource: { color: '#3CB87A', light: '#EEFFF6', label: 'Resource' },
  activity: { color: '#FF6B6B', light: '#FFEEEE', label: 'Activity' },
}

export const FILTERS = [
  { id: 'all',      label: 'All',       color: '#4A4A4A' },
  { id: 'question', label: 'Questions', color: '#5599EE' },
  { id: 'tip',      label: 'Tips',      color: '#FF9A3C' },
  { id: 'story',    label: 'Stories',   color: '#CC66FF' },
  { id: 'resource', label: 'Resources', color: '#3CB87A' },
  { id: 'activity', label: 'Activities',color: '#FF6B6B' },
]
